FROM mysql:8
ADD homebox.sql /docker-entrypoint-initdb.d

#  docker build -t bd-img -f Dockerfile ../../database
#  sudo docker run --name database-homebox --network network-homebox -e MYSQL_ROOT_PASSWORD=urubu100 -e MYSQL_DATABASE=homebox  -e MYSQL_USER=homebox -e MYSQL_PASSWORD=Homebox265@ -d bd-img
