Resources:
  rtbHomebox:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: rtb-homebox

  routeTableAssocName:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetPriAZ1
      RouteTableId: !Ref rtbHomebox

  routeName:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref rtbHomebox
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IgwHomebox
