Resources:
  SubnetPubAZ1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.0.70/26
      MapPublicIpOnLaunch: true
      AvailabilityZoneId: use1-az1
      Tags:
        - Key: Name
          Value: sub-az1-pub-homebox

  SubnetPriAZ1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.0.0/26
      MapPublicIpOnLaunch: false
      AvailabilityZoneId: use1-az1
      Tags:
        - Key: Name
          Value: sub-az1-pri-homebox

  SubnetPubAZ2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1c
      VpcId: !Ref VPC
      CidrBlock: 10.0.0.128/26
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: sub-az2-pub-homebox

