Resources:
  # LOAD BALANCER

  EC2LoadBalancerAZ1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-09f0703ad9e1c92a2
      KeyName: ch28082022Publica
      InstanceType: t2.medium
      SubnetId: !Ref SubnetPubAZ1
      SecurityGroupIds:
        - !GetAtt SecurityGroupLBPub.GroupId
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            VolumeType: "gp2"
            VolumeSize: "20"
      Tags:
        - Key: Name
          Value: ec2-pub-lb-az1

  eipNameLoadBalancer:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !Ref EC2LoadBalancerAZ1

  # AZ1
  EC2FrontEndAZ1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-00bfec5d1aed3fa1f
      KeyName: ch28082022Publica
      InstanceType: t2.medium
      SubnetId: !Ref SubnetPubAZ1
      SecurityGroupIds:
        - !GetAtt SecurityGroupPub.GroupId
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            VolumeType: "gp2"
            VolumeSize: "100"
      Tags:
        - Key: Name
          Value: ec2-pub-front-end-az1

  eipNameFrontAz1:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !Ref eipNameFrontAz1

  ##########################################
  EC2PrivateAZ1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-07beba960ae6860e6
      KeyName: ch28082022Privada
      InstanceType: t2.medium
      SubnetId: !Ref SubnetPriAZ1
      SecurityGroupIds:
        - !GetAtt SecurityGroupPri.GroupId
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            VolumeType: "gp2"
            VolumeSize: "100"
      Tags:
        - Key: Name
          Value: ec2-priv-back-bd-az1

  eipNameBackEndAz1:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !Ref eipNameBackEndAz1

  # AZ2

  EC2FrontEndAZ2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-01b08baa2e3d2e3ac
      KeyName: ch28082022Publica
      InstanceType: t2.medium
      SubnetId: !Ref SubnetPubAZ2
      SecurityGroupIds:
        - !GetAtt SecurityGroupPubAz2.GroupId
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            VolumeType: "gp2"
            VolumeSize: "100"
      Tags:
        - Key: Name
          Value: ec2-pub-front-end-az2

  eipNameFrontEndAz2:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !Ref eipNameFrontEndAz2
