Resources:
  #EC2FrontEnd:
  #  Type: AWS::EC2::Instance
  #  Properties:
  #    ImageId: ami-08d4ac5b634553e16
  #    KeyName: ch28082022Pub
  #    InstanceType: t2.micro
  #    SubnetId: !Ref SubnetPubAZ1
  #    SecurityGroups:
  #      - !Ref SecurityGroupPub
  #    BlockDeviceMappings:
  #    - DeviceName: "/dev/sda1"
  #      Ebs:
  #        VolumeType: "gp2"
  #        VolumeSize: "8"

  EC2Private:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-08d4ac5b634553e16
      KeyName: ch28082022Pri
      InstanceType: t2.micro
      SubnetId: !Ref SubnetPriAZ1
      SecurityGroups:
        - !Ref SecurityGroupPri
      BlockDeviceMappings:
      - DeviceName: "/dev/sda1"
        Ebs:
          VolumeType: "gp2"
          VolumeSize: "8"
