Resources:
  # LOAD BALANCER

  EC2LoadBalancerAZ1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-00f19e43bb4a97834
      KeyName: ch28082022Publica
      InstanceType: t2.medium
      SubnetId: !Ref SubnetPubAZ1
      SecurityGroupIds:
        - !GetAtt SecurityGroupLBPub.GroupId
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            VolumeType: "gp2"
            VolumeSize: "20"
      Tags:
        - Key: Name
          Value: ec2-pub-lb-az1

  # AZ1
  EC2FrontEndAZ1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-00bbce6216fe0771b
      KeyName: ch28082022Publica
      InstanceType: t2.medium
      SubnetId: !Ref SubnetPubAZ1
      SecurityGroupIds:
        - !GetAtt SecurityGroupPub.GroupId
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            VolumeType: "gp2"
            VolumeSize: "100"
      Tags:
        - Key: Name
          Value: ec2-pub-front-end-az1

  EC2PrivateAZ1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0bc5470e63ead1b1d
      KeyName: ch28082022Privada
      InstanceType: t2.medium
      SubnetId: !Ref SubnetPriAZ1
      SecurityGroupIds:
        - !GetAtt SecurityGroupPri.GroupId
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            VolumeType: "gp2"
            VolumeSize: "100"
      Tags:
        - Key: Name
          Value: ec2-priv-back-bd-az1

  # AZ2

  EC2FrontEndAZ2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-09544054149edeefc
      KeyName: ch28082022Publica
      InstanceType: t2.medium
      SubnetId: !Ref SubnetPubAZ2
      SecurityGroupIds:
        - !GetAtt SecurityGroupPubAz2.GroupId
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            VolumeType: "gp2"
            VolumeSize: "100"
      Tags:
        - Key: Name
          Value: ec2-pub-front-end-az2

