service: homebox-core

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.8

package:
  individually: true
  patterns:
    - "!venv/**"
    - "!test/**"
    - "!buildspec.yml"
    - "!functions/**"
    - "!README.md"
    - "!node_modules/**"
    - "!package-lock.json"
    - "!package.json"
    - "!resources.yml"
    - "!src/**"
    - "!resources/**"
    - "!step_functions.yml"

resources:
  - ${file(resources/infra/vpc.yml)}
  - ${file(resources/infra/subnet.yml)}
  - ${file(resources/infra/internet-gateway.yml)}
  - ${file(resources/security/security-group.yml)}
  - ${file(resources/security/key-pair.yml)}
  - ${file(resources/vm/ec2.yml)}
  - ${file(resources/SNS/sns.yml)}
  - ${file(resources/lambda/url.yml)}

functions:
  DistanceCalculation: ${file(functions/distance_calculation/distance_calculation.yml)}
  GetCredentials: ${file(functions/get-credentials/get-credentials.yml)}
  GetUsersDistance: ${file(functions/get-users-distance/get-users-distance.yml)}
  PutUsersDistance: ${file(functions/put-users-distance/put-users-distance.yml)}
  PutUsersDistance: ${file(functions/put-users-distance/put-users-distance-full.yml)}
